In [32]:
import pandas as pd
import numpy as np

In [40]:
df = pd.read_csv("./data/olist_products_dataset.csv")

In [42]:
df[df["product_photos_qty"] == 225.0]

Empty DataFrame
Columns: [product_id, product_name_lenght, product_description_lenght, product_photos_qty, product_weight_g, product_length_cm, product_height_cm, product_width_cm, product_category_name]
Index: []

In [35]:
cols = [
    "product_name_lenght",
    "product_description_lenght",
    "product_photos_qty"
]


df[cols] = df[cols].astype("Int64")
# df[cols] = df[cols].fillna(-100)
# df[cols] = df[cols].astype("int64") 
# df[cols] = df[cols].replace(-100, np.nan)
# for i in cols: 
    # if df[i].isna().values:/
        # print(df[i])
    # print(df[i].isna().values)
    # if pd.isna(df[i]):
        # continue
    # df[i] = df[i].astype(int)
    #

In [39]:
df

,product_id,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name
0,1e9e8ef04dbcff4541ed26657ea517e5,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,45.0,67.0,2.0,12300.0,40.0,40.0,40.0,furniture_decor
32947,bf4538d88321d0fd4412a93c974510e6,41.0,971.0,1.0,1700.0,16.0,19.0,16.0,construction_tools_lights
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,50.0,799.0,1.0,1400.0,27.0,7.0,27.0,bed_bath_table
32949,83808703fc0706a22e264b9d75f04a2e,60.0,156.0,2.0,700.0,31.0,13.0,20.0,computers_accessories
32950,106392145fca363410d287a815be6de4,58.0,309.0,1.0,2083.0,12.0,2.0,7.0,bed_bath_table

In [37]:
df.to_csv("./data/olist_products_dataset.csv", index=False)